apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube
  labels:
    app: kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube
  template:
    metadata:
      labels:
        app: kube
    spec:
      containers:
      - name: kube
        image: diogofrmota/helloworld
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        imagePullPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  name: kube
spec:
  selector:
    app: kube
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80